### ISSUE TITLE
Enable "!include($fileName)" parsing in before and after sections

### ISSUE THREAD

**Issue by fabricemoreau** [allonzy/artillery-plugin-json-include#2]
This plugin is very useful.

I noticed the `!include($fileName)` replacement with json content is not enabled in the `before` and `after` sections of the artillery yaml. (In any `flow` section)

Is it possible to enable it?

Regards,

**Comment by geersch** [comment]
Noticed the same behaviour, the JSON content is not included if you use this plugin in a `before` or `after` section. Works fine in a `scenario`. Would be handy if this was supported too.

**Comment by allonzy** [comment]
I'll look into that, but due of the plugin lifecycle it might not be possible

**Comment by allonzy** [comment]
Sorry, not possible due to plugins lifecycles
